from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def create_pdf(summary):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    elements = []

    title = Paragraph(
        "<b>InsightAI - Executive Report</b>",
        styles["Title"]
    )

    elements.append(title)

    elements.append(Spacer(1, 20))

    subtitle = Paragraph(
        "AI Generated Business Intelligence Report",
        styles["Heading2"]
    )

    elements.append(subtitle)

    elements.append(Spacer(1, 20))

    heading = Paragraph(
        "<b>Executive Summary</b>",
        styles["Heading2"]
    )

    elements.append(heading)

    elements.append(Spacer(1, 10))

    elements.append(
        Paragraph(summary, styles["BodyText"])
    )

    elements.append(Spacer(1, 20))

    table_data = [
        ["Generated By", "InsightAI"],
        ["Report Type", "Business Intelligence"],
        ["AI Model", "Llama 3.3 70B (Groq)"],
    ]

    table = Table(table_data)

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
            ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
        ])
    )

    elements.append(table)

    doc.build(elements)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf